language: python
python:
  - "3.4"
  - "3.5"
install: "pip install -r requirements.txt"
before_script: "cp elearning/settings_local.EXAMPLE.py elearning/settings_local.py"
script: "python manage.py init"
