"""
Django settings for elearning project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/
from elearning.settings_local import DEBUG, BASE_DIR, DATABASES, SECRET_KEY, PROJECT_NAME, SHELL_PLUS

# Application definition
INSTALLED_APPS = (
    # See https://github.com/dyve/django-bootstrap3
    'bootstrap3',
    # See https://github.com/darklow/django-suit
    'suit',

    # Uncomment the next line to enable admin documentation:
    # 'django.contrib.admindocs',
    # Uncomment the next line to enable the admin:
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',


    # See https://github.com/llazzaro/django-scheduler
    'schedule',

    # See https://github.com/django-ckeditor/django-ckeditor
    'ckeditor',

    # See https://github.com/pydanny/django-wysiwyg/
    'django_wysiwyg',

    'django_extensions',
    'debug_toolbar',

    # See https://github.com/hovel/pybbm
    'pybb',

    'elearning'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'pybb.middleware.PybbMiddleware',
)

ROOT_URLCONF = 'elearning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': DEBUG,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pybb.context_processors.processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'elearning.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
LANGUAGE_CODE = 'en-us'

# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
TIME_ZONE = 'Europe/Bucharest'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR + "/static/"


# Redirect to index after login
LOGIN_REDIRECT_URL = 'index'

# Login url
LOGIN_URL = 'login'

# See http://django-suit.readthedocs.org/en/develop/configuration.html
SUIT_CONFIG = {
    'ADMIN_NAME': 'Admin Area'
}


# See http://django-bootstrap3.readthedocs.org/en/latest/settings.html
JQUERY_URL = STATIC_URL + 'elearning/js/vendors/jquery.min.js'
BOOTSTRAP3 = {
    # The URL to the jQuery JavaScript file
    'jquery_url': JQUERY_URL,

    # The Bootstrap base URL
    'base_url': STATIC_URL + 'elearning/',

    # The complete URL to the Bootstrap CSS file (None means derive it from base_url)
    'css_url': None,

    # The complete URL to the Bootstrap CSS file (None means no theme)
    'theme_url': None,

    # The complete URL to the Bootstrap JavaScript file (None means derive it from base_url)
    'javascript_url': STATIC_URL + 'elearning/js/vendors/bootstrap.min.js',

    # Include jQuery with Bootstrap JavaScript (affects django-bootstrap3 template tags)
    'include_jquery': True,
}

# See https://github.com/django-ckeditor/django-ckeditor#required
CKEDITOR_JQUERY_URL = JQUERY_URL

# See https://github.com/pydanny/django-wysiwyg/#using-the-ckeditor
DJANGO_WYSIWYG_FLAVOR = "ckeditor"
DJANGO_WYSIWYG_MEDIA_URL = STATIC_URL

# See http://pybbm.readthedocs.org/en/latest/index.html
PYBB_MARKUP = 'markdown'
PYBB_SMILES_PREFIX = STATIC_URL + 'pybb/emoticons/'
PYBB_ATTACHMENT_ENABLE = True
